# This file was generated by GoReleaser. DO NOT EDIT.
cask "yaml2hcl" do
  version "1.0.5"

  on_macos do
    on_arm do
      sha256 "d2e7d40179812857520e9f8bb89779fa0652c07493f7906e0055f5064d2f8eb9"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91b1b888ce2a7315dcaaad23998752018fe7b7efde973a8ddc3329a97a55e4dc"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3bdc8b33fded87c1c9ec2a39b3a915abdd1ab96b33432a353b512cf5909bc653"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "57352ca1ced955748caca9976f0442b0548fc12f4f98178a385986ae954cb7ad"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yaml2hcl"
  desc "CLI tool to convert Helm values to HCL"
  homepage "https://github.com/scub/yaml2hcl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yaml2hcl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yaml2hcl"]
    end
  end

  # No zap stanza required
end
