# This file was generated by GoReleaser. DO NOT EDIT.
cask "yaml2hcl" do
  version "0.0.2-test"

  on_macos do
    on_arm do
      sha256 "07f76e46af67df14d022b44a7702ef55c8b1ce080c6ec9ca9145ce8c13b33190"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f02f8fac4c64c918bcc1ea33e6ab224d303820a2f460482ed492eccce9125d8"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a9e4e1a9dba7e29dedf3e74e80791056adc83709a8283faed5ecd34c9158d68"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cbc923c4e55910007f5252ca8d4327884a4c9ca5a29706d15b5e9833744a38e"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yaml2hcl"
  desc "CLI tool to convert Helm values to HCL"
  homepage "https://github.com/scub/yaml2hcl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yaml2hcl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yaml2hcl"]
    end
  end

  # No zap stanza required
end
