# This file was generated by GoReleaser. DO NOT EDIT.
cask "yaml2hcl" do
  version "0.0.3-test"

  on_macos do
    on_arm do
      sha256 "5403cd32139948a5c7abdf2726986dc738ab283cb145020324497fe4875b2d91"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c5076ac95f3b1533e8abcf5366694973039e6e08566eb43126494cf6514a860"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6cc7b2fd7ad6c1976239f00dd3fceab7e2ce81ad319c61da32eb1591e4ac8e53"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc652e69857b707f0f2bedd9ba8f9edf860f14c0d356f4f9c88776e7ec1b1dd8"
      url "https://github.com/scub/yaml2hcl/releases/download/v#{version}/yaml2hcl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yaml2hcl"
  desc "CLI tool to convert Helm values to HCL"
  homepage "https://github.com/scub/yaml2hcl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yaml2hcl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yaml2hcl"]
    end
  end

  # No zap stanza required
end
