# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaml2hcl < Formula
  desc "CLI tool to monitor API health endpoints"
  homepage "https://github.com/scub/yaml2hcl"
  version "0.0.0-dev"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scub/yaml2hcl/releases/download/v0.0.0-dev/yaml2hcl_0.0.0-dev_darwin_amd64.tar.gz"
      sha256 "93a9d34054102164c9c1d63bb3a05b7f39fe94c85abc174315c03f28cd9c05d1"

      define_method(:install) do
        bin.install "yaml2hcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scub/yaml2hcl/releases/download/v0.0.0-dev/yaml2hcl_0.0.0-dev_darwin_arm64.tar.gz"
      sha256 "f4816be21b6c31802e2184cb0f5f1df58997626659c652715043458faa3777fb"

      define_method(:install) do
        bin.install "yaml2hcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scub/yaml2hcl/releases/download/v0.0.0-dev/yaml2hcl_0.0.0-dev_linux_amd64.tar.gz"
      sha256 "12da254db4b8be646836b0bcbbafd54c194cacdc8a37305070212c575e2c8d85"
      define_method(:install) do
        bin.install "yaml2hcl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scub/yaml2hcl/releases/download/v0.0.0-dev/yaml2hcl_0.0.0-dev_linux_arm64.tar.gz"
      sha256 "991fab5fbef902f649eff77597f79e7bc648c3cc2b6dd81dd04f38737abc0bbb"
      define_method(:install) do
        bin.install "yaml2hcl"
      end
    end
  end

  test do
    system "#{bin}/yaml2hcl", "version"
  end
end
